# Generated by Django 2.2.4 on 2019-08-28 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_make_returned', 'Set book as returned'),)},
        ),
    ]
